workflows:
  unity-ios-build:
    name: Unity iOS Build
    environment:
      vars:
        UNITY_SERIAL: $UNITY_SERIAL # مفتاح الترخيص الخاص بـ Unity (للمشاريع المدفوعة)
      unity:
        version: "2021.3.18f1" # ضع إصدار Unity الذي تستخدمه
      xcode:
        version: "15.0" # إصدار Xcode المثبت في بيئة Codemagic
    scripts:
      - name: Set up Unity
        script: |
          echo "Setting up Unity environment"
      - name: Build Unity Project for iOS
        script: |
          unity-editor \
            -batchmode \
            -nographics \
            -quit \
            -projectPath ./ \
            -buildTarget iOS \
            -customBuildTarget ios \
            -outputPath ./build/ios
      - name: Export IPA using Xcode
        script: |
          cd ./build/ios
          xcodebuild \
            -workspace Unity-iPhone.xcworkspace \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath ./build/UnityApp.xcarchive
          xcodebuild \
            -exportArchive \
            -archivePath ./build/UnityApp.xcarchive \
            -exportOptionsPlist ./ExportOptions.plist \
            -exportPath ./build/UnityApp
    artifacts:
      - build/UnityApp/game.ipa # تحديد ملف IPA الناتج
